# Generated by Django 3.1.5 on 2021-05-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('building', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('address_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('otp', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(null=True)),
                ('last_change_date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
