# Generated by Django 3.1.5 on 2021-05-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.IntegerField(null=True),
        ),
    ]
