# Generated by Django 3.1.5 on 2021-05-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_website', '0002_address_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='last_change_date_time',
        ),
        migrations.RemoveField(
            model_name='onetimepassword',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='onetimepassword',
            name='status',
        ),
    ]
