# Generated by Django 3.1.5 on 2021-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_website', '0003_auto_20210530_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='last_change_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='otp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
