# Generated by Django 3.1.5 on 2021-05-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_website', '0004_auto_20210530_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='last_change_date_time',
        ),
        migrations.RemoveField(
            model_name='onetimepassword',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='onetimepassword',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='onetimepassword',
            name='status',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='bishal_temp',
            field=models.IntegerField(null=True),
        ),
    ]
