# Generated by Django 3.1.5 on 2021-05-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20210428_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_id', models.IntegerField(null=True)),
                ('business_id', models.IntegerField(null=True)),
                ('customer_id', models.IntegerField(null=True)),
            ],
        ),
    ]
