# Generated by Django 3.1.5 on 2021-05-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20210504_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_id', models.IntegerField(null=True)),
                ('business_id', models.IntegerField(null=True)),
                ('customer_id', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
