# Generated by Django 3.1.5 on 2021-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address_id',
            field=models.IntegerField(null=True),
        ),
    ]
