# Generated by Django 3.1.5 on 2021-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_orders_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
