# Generated by Django 3.1.5 on 2021-06-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_orders_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
