# Generated by Django 3.1.5 on 2021-06-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_auto_20210602_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_status',
            name='active',
            field=models.IntegerField(null=True),
        ),
    ]
