# Generated by Django 3.1.5 on 2021-06-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_orders_status_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders_status',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
