# Generated by Django 3.1.5 on 2021-06-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_auto_20210604_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='orders_status',
            name='reason',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
