# Generated by Django 3.1.5 on 2021-06-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_auto_20210613_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('building', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('address_type', models.CharField(max_length=100, null=True)),
                ('default', models.IntegerField(null=True)),
            ],
        ),
    ]
