# Generated by Django 3.1.5 on 2021-06-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_otp',
            field=models.IntegerField(null=True),
        ),
    ]
