# Generated by Django 3.1.5 on 2021-06-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_orders_order_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_id', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('total_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product_type_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
    ]
