# Generated by Django 3.1.5 on 2021-06-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0017_order_products_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_charge',
            field=models.IntegerField(null=True),
        ),
    ]
