# Generated by Django 3.1.5 on 2021-06-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0018_orders_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_order_amount',
            field=models.IntegerField(null=True),
        ),
    ]
