# Generated by Django 3.1.5 on 2021-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
