# Generated by Django 3.1.5 on 2021-06-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0021_orders_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_mode',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.BooleanField(default=True),
        ),
    ]
