# Generated by Django 3.1.5 on 2021-06-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0022_auto_20210627_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
