# Generated by Django 3.1.5 on 2021-06-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0024_auto_20210627_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='checksumhash',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
