# Generated by Django 3.1.5 on 2021-06-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0025_auto_20210627_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='respmsg',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
