# Generated by Django 3.1.5 on 2021-06-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0026_auto_20210627_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_address',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
