# Generated by Django 3.2.3 on 2021-06-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0018_auto_20210624_2351'),
        ('Customer', '0027_order_address_order_id'),
    ]

    operations = [
    ]
