# Generated by Django 3.2.3 on 2021-07-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0029_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='privacy_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
