# Generated by Django 3.1.5 on 2021-04-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_category_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='unit',
        ),
        migrations.AddField(
            model_name='business',
            name='initial_walet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product_type',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product_type',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product_type',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
    ]
