# Generated by Django 3.1.5 on 2021-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0004_auto_20210428_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
