# Generated by Django 3.1.5 on 2021-04-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0005_business_business_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_id',
            new_name='business_key',
        ),
    ]
