# Generated by Django 3.1.5 on 2021-05-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0006_auto_20210428_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='product_type_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
