# Generated by Django 3.1.5 on 2021-05-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0007_product_type_product_type_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./static/media'),
        ),
        migrations.AddField(
            model_name='product_type',
            name='pack_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_type',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
