# Generated by Django 3.1.5 on 2021-05-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0008_auto_20210514_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./static/media'),
        ),
    ]
