# Generated by Django 3.1.5 on 2021-05-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0009_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='./static/media'),
        ),
        migrations.AddField(
            model_name='business',
            name='dp_image',
            field=models.ImageField(blank=True, null=True, upload_to='./static/media'),
        ),
    ]
