# Generated by Django 3.1.5 on 2021-05-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0010_auto_20210521_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
