# Generated by Django 3.1.5 on 2021-05-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0011_business_business_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_category',
            new_name='category',
        ),
    ]
