# Generated by Django 3.1.5 on 2021-05-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0012_auto_20210523_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
    ]
