# Generated by Django 3.1.5 on 2021-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0013_remove_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
