# Generated by Django 3.1.5 on 2021-06-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0014_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='mrp',
            field=models.IntegerField(null=True),
        ),
    ]
