# Generated by Django 3.1.5 on 2021-06-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0015_product_type_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='payment_choice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
