# Generated by Django 3.1.5 on 2021-06-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0016_business_payment_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='initial_walet',
        ),
        migrations.RemoveField(
            model_name='business',
            name='subscription_amount',
        ),
        migrations.AddField(
            model_name='business',
            name='delivery_charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='minimum_delivery_amount',
            field=models.IntegerField(null=True),
        ),
    ]
