# Generated by Django 3.1.5 on 2021-06-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0017_auto_20210626_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='delivery_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='business',
            name='minimum_delivery_amount',
            field=models.IntegerField(default=0),
        ),
    ]
