# Generated by Django 3.1.5 on 2021-06-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0018_auto_20210626_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='delivery_type',
            field=models.CharField(default='free', max_length=100),
        ),
    ]
