# Generated by Django 3.2.3 on 2021-06-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0016_auto_20210624_2351'),
        ('Business', '0019_business_delivery_type'),
    ]

    operations = [
    ]
